# Default values for hello-universe-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "hello-universe"

deploymentName: "hello-universe"

deploymentCustomAttrs:
  deployment_1:
    replicas: 1
    deploymentNameSuffix: "1"
    containerName: "hello-universe-python"
  # deployment_2:
  #   replicas: 1
  #   deploymentNameSuffix: "2"
  #   containerName: "hola-universe-python"

image:
  registry: local
  repository: hello-universe
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: NodePort
  protocol: TCP
  targetPort: pythonport
  port: 9999
  nodePort: 32000

resources:
  limits:
    cpu: "0.30"
    memory: 300M
  requests:
    cpu: "0.10"
    memory: 180M

nodeSelector:
  kubernetes.io/hostname: docker-desktop
